[2024-08-08T15:55:24.985+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T15:55:25.079+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finnhub_data_streaming.stream_data manual__2024-08-08T15:55:18.644889+00:00 [queued]>
[2024-08-08T15:55:25.098+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finnhub_data_streaming.stream_data manual__2024-08-08T15:55:18.644889+00:00 [queued]>
[2024-08-08T15:55:25.101+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-08T15:55:25.127+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stream_data> on 2024-08-08 15:55:18.644889+00:00
[2024-08-08T15:55:25.138+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-08T15:55:25.139+0000] {standard_task_runner.py:64} INFO - Started process 318 to run task
[2024-08-08T15:55:25.137+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'finnhub_data_streaming', 'stream_data', 'manual__2024-08-08T15:55:18.644889+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/topic.py', '--cfg-path', '/tmp/tmpn2x83h_x']
[2024-08-08T15:55:25.141+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask stream_data
[2024-08-08T15:55:25.177+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-08T15:55:25.280+0000] {task_command.py:426} INFO - Running <TaskInstance: finnhub_data_streaming.stream_data manual__2024-08-08T15:55:18.644889+00:00 [running]> on host 552be2a98828
[2024-08-08T15:55:25.481+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finnhub_data_streaming' AIRFLOW_CTX_TASK_ID='stream_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T15:55:18.644889+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-08T15:55:18.644889+00:00'
[2024-08-08T15:55:25.485+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T15:55:25.560+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T15:55:25.561+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/topic.py", line 59, in stream_data
    message = json.dumps(formatted_data).encode('utf-8')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
[2024-08-08T15:55:25.585+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=finnhub_data_streaming, task_id=stream_data, run_id=manual__2024-08-08T15:55:18.644889+00:00, execution_date=20240808T155518, start_date=20240808T155525, end_date=20240808T155525
[2024-08-08T15:55:25.606+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 73 for task stream_data (Object of type datetime is not JSON serializable; 318)
[2024-08-08T15:55:25.638+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-08T15:55:25.672+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-08T15:55:25.675+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
