[2024-08-01T08:38:19.763+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T08:38:19.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finnhub_data_streaming.get_data scheduled__2024-01-01T11:32:00+00:00 [queued]>
[2024-08-01T08:38:19.823+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finnhub_data_streaming.get_data scheduled__2024-01-01T11:32:00+00:00 [queued]>
[2024-08-01T08:38:19.823+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-01T08:38:19.886+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-01-01 11:32:00+00:00
[2024-08-01T08:38:19.892+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1047) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-01T08:38:19.893+0000] {standard_task_runner.py:64} INFO - Started process 1053 to run task
[2024-08-01T08:38:19.893+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'finnhub_data_streaming', 'get_data', 'scheduled__2024-01-01T11:32:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/topic.py', '--cfg-path', '/tmp/tmpw1jeykz7']
[2024-08-01T08:38:19.895+0000] {standard_task_runner.py:91} INFO - Job 249: Subtask get_data
[2024-08-01T08:38:19.913+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T08:38:19.952+0000] {task_command.py:426} INFO - Running <TaskInstance: finnhub_data_streaming.get_data scheduled__2024-01-01T11:32:00+00:00 [running]> on host 0baaf0b4c9a1
[2024-08-01T08:38:20.041+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finnhub_data_streaming' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T11:32:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T11:32:00+00:00'
[2024-08-01T08:38:20.042+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T08:38:20.858+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T08:38:20.860+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/topic.py", line 29, in get_data
    quote_data = finnhub_client.quote('AAPL')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/finnhub/client.py", line 205, in quote
    return self._get("/quote", params={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/finnhub/client.py", line 71, in _get
    return self._request("get", path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/finnhub/client.py", line 41, in _request
    return self._handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/finnhub/client.py", line 46, in _handle_response
    raise FinnhubAPIException(response)
finnhub.exceptions.FinnhubAPIException: FinnhubAPIException(status_code: 429): API limit reached. Please try again later. Remaining Limit: 0
[2024-08-01T08:38:20.882+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=finnhub_data_streaming, task_id=get_data, run_id=scheduled__2024-01-01T11:32:00+00:00, execution_date=20240101T113200, start_date=20240801T083819, end_date=20240801T083820
[2024-08-01T08:38:20.908+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 249 for task get_data (FinnhubAPIException(status_code: 429): API limit reached. Please try again later. Remaining Limit: 0; 1053)
[2024-08-01T08:38:20.949+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-01T08:38:20.972+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
