[2024-08-08T02:28:02.825+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T02:28:02.879+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-08-07T00:00:00+00:00 [queued]>
[2024-08-08T02:28:02.892+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-08-07T00:00:00+00:00 [queued]>
[2024-08-08T02:28:02.893+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-08T02:28:02.913+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-08-07 00:00:00+00:00
[2024-08-08T02:28:02.928+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=241) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-08T02:28:02.930+0000] {standard_task_runner.py:64} INFO - Started process 246 to run task
[2024-08-08T02:28:02.927+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2024-08-07T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpbqk66rgl']
[2024-08-08T02:28:02.932+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask stream_data_from_api
[2024-08-08T02:28:02.959+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-08T02:28:03.018+0000] {task_command.py:426} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2024-08-07T00:00:00+00:00 [running]> on host 1c8fec21bc35
[2024-08-08T02:28:03.173+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-07T00:00:00+00:00'
[2024-08-08T02:28:03.174+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T02:28:32.369+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-08-08T02:28:32.372+0000] {process_utils.py:132} INFO - Sending 15 to group 246. PIDs of all processes in the group: [246]
[2024-08-08T02:28:32.373+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 246
[2024-08-08T02:28:32.997+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-08T02:28:32.998+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T02:28:33.039+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_stream.py", line 65, in stream_data
    producer.poll(1)  # Poll to handle delivery reports
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-08-08T02:28:33.097+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, run_id=scheduled__2024-08-07T00:00:00+00:00, execution_date=20240807T000000, start_date=20240808T022802, end_date=20240808T022833
[2024-08-08T02:28:33.176+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=246, status='terminated', exitcode=2, started='02:28:02') (246) terminated with exit code 2
[2024-08-08T02:28:33.178+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 143
[2024-08-08T02:28:33.251+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-08T02:28:33.324+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
